name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Very Easy Challenges
      id: test-very-easy-challenges
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Very Easy Challenges
        setup-command: npm install
        command: npm test tests/veryEasyChallenges.test.js
        timeout: 2
        max-score: 10
    - name: Test Easy Challenges
      id: test-easy-challenges
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Easy Challenges
        setup-command: npm install
        command: npm test tests/easyChallenges.test.js
        timeout: 2
        max-score: 10
    - name: Test Harder Challenges
      id: test-harder-challenges
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Harder Challenges
        setup-command: npm install
        command: npm test tests/harderChallenges.test.js
        timeout: 2
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-VERY-EASY-CHALLENGES_RESULTS: "${{steps.test-very-easy-challenges.outputs.result}}"
        TEST-EASY-CHALLENGES_RESULTS: "${{steps.test-easy-challenges.outputs.result}}"
        TEST-HARDER-CHALLENGES_RESULTS: "${{steps.test-harder-challenges.outputs.result}}"
      with:
        runners: test-very-easy-challenges,test-easy-challenges,test-harder-challenges
